package tandu.activities

import tandu.i18n.Lang

/** Single-option choices for the "Would you rather" activity. Each
  * entry is a self-contained predicate phrased so it fits naturally
  * after the language's "Would you rather..." prefix. Pairs are drawn
  * at random from this pool — so every entry has to make sense next
  * to any other. Weird pairings are a feature, not a bug.
  *
  * Add freely. Lists do not need to match across languages.
  */
object WouldYouRatherBank:

  val en: Vector[String] = Vector(
    "fly",
    "be invisible",
    "talk to animals",
    "speak every language",
    "live in a castle",
    "live in a treehouse",
    "swim with dolphins",
    "ride a dragon",
    "have a pet dinosaur",
    "have a pet unicorn",
    "eat pizza every day",
    "eat ice cream every day",
    "always be too hot",
    "always be too cold",
    "be as small as a mouse",
    "be as tall as a giraffe",
    "have super speed",
    "have super strength",
    "read minds",
    "see the future",
    "live on the moon",
    "live underwater",
    "have wings",
    "have a tail",
    "be a wizard",
    "be a knight",
    "visit the dinosaurs",
    "travel to the future",
    "ride a horse",
    "ride a camel",
    "own a chocolate fountain",
    "own a candy garden",
    "control fire",
    "control water",
    "always wear pajamas",
    "always wear fancy clothes",
    "eat only sweet food",
    "eat only salty food",
    "hiccup forever",
    "sneeze every five minutes",
    "have a robot best friend",
    "have a dragon best friend",
    "travel by hot-air balloon",
    "travel by submarine",
    "have it always rain",
    "have it always snow",
    "be famous",
    "live in a cave",
    "sing instead of speaking",
    "dance instead of walking",
    "shrink to ant size",
    "grow to giant size",
    "be a pirate",
    "be an astronaut",
    "find a treasure chest",
    "find a magic lamp",
    "have a third arm",
    "have laser eyes",
    "own a flying skateboard",
    "have a magic wand",
    "only whisper",
    "teleport anywhere",
    "travel through time",
    "sleep in a hammock",
    "paint with your toes"
  )

  val pl: Vector[String] = Vector(
    "latać",
    "być niewidzialnym",
    "rozmawiać ze zwierzętami",
    "znać wszystkie języki",
    "mieszkać w zamku",
    "mieszkać w domku na drzewie",
    "pływać z delfinami",
    "latać na smoku",
    "mieć dinozaura jako pupila",
    "mieć jednorożca jako pupila",
    "jeść codziennie pizzę",
    "jeść codziennie lody",
    "ciągle czuć gorąco",
    "ciągle marznąć",
    "być małym jak myszka",
    "być wysokim jak żyrafa",
    "mieć super szybkość",
    "mieć super siłę",
    "czytać w myślach",
    "widzieć przyszłość",
    "mieszkać na księżycu",
    "mieszkać pod wodą",
    "mieć skrzydła",
    "mieć ogon",
    "być czarodziejem",
    "być rycerzem",
    "odwiedzić dinozaury",
    "podróżować do przyszłości",
    "jeździć na koniu",
    "jeździć na wielbłądzie",
    "mieć fontannę czekoladową",
    "mieć ogród z cukierków",
    "sterować ogniem",
    "sterować wodą",
    "zawsze chodzić w piżamie",
    "zawsze chodzić w eleganckim stroju",
    "jeść tylko słodkie",
    "jeść tylko słone",
    "mieć czkawkę bez końca",
    "kichać co pięć minut",
    "mieć robota jako najlepszego przyjaciela",
    "mieć smoka jako najlepszego przyjaciela",
    "podróżować balonem",
    "podróżować łodzią podwodną",
    "mieć ciągle deszcz",
    "mieć ciągle śnieg",
    "być sławnym",
    "mieszkać w jaskini",
    "śpiewać zamiast mówić",
    "tańczyć zamiast chodzić",
    "skurczyć się do rozmiaru mrówki",
    "urosnąć do rozmiaru olbrzyma",
    "być piratem",
    "być astronautą",
    "znaleźć skrzynię ze skarbem",
    "znaleźć magiczną lampę",
    "mieć trzecią rękę",
    "mieć laserowe oczy",
    "mieć latającą deskorolkę",
    "mieć magiczną różdżkę",
    "tylko szeptać",
    "teleportować się dokądkolwiek",
    "podróżować w czasie",
    "spać w hamaku",
    "malować palcami u stóp"
  )

  val es: Vector[String] = Vector(
    "volar",
    "ser invisible",
    "hablar con los animales",
    "hablar todos los idiomas",
    "vivir en un castillo",
    "vivir en una casa del árbol",
    "nadar con delfines",
    "montar un dragón",
    "tener un dinosaurio de mascota",
    "tener un unicornio de mascota",
    "comer pizza todos los días",
    "comer helado todos los días",
    "tener siempre calor",
    "tener siempre frío",
    "ser pequeño como un ratón",
    "ser alto como una jirafa",
    "tener super velocidad",
    "tener super fuerza",
    "leer mentes",
    "ver el futuro",
    "vivir en la luna",
    "vivir bajo el agua",
    "tener alas",
    "tener cola",
    "ser un mago",
    "ser un caballero",
    "visitar a los dinosaurios",
    "viajar al futuro",
    "montar a caballo",
    "montar en camello",
    "tener una fuente de chocolate",
    "tener un jardín de caramelos",
    "controlar el fuego",
    "controlar el agua",
    "llevar siempre pijama",
    "llevar siempre ropa elegante",
    "comer solo dulce",
    "comer solo salado",
    "tener hipo para siempre",
    "estornudar cada cinco minutos",
    "tener un robot como mejor amigo",
    "tener un dragón como mejor amigo",
    "viajar en globo",
    "viajar en submarino",
    "que llueva siempre",
    "que nieve siempre",
    "ser famoso",
    "vivir en una cueva",
    "cantar en vez de hablar",
    "bailar en vez de caminar",
    "encoger al tamaño de una hormiga",
    "crecer al tamaño de un gigante",
    "ser pirata",
    "ser astronauta",
    "encontrar un cofre del tesoro",
    "encontrar una lámpara mágica",
    "tener un tercer brazo",
    "tener ojos láser",
    "tener un monopatín volador",
    "tener una varita mágica",
    "solo susurrar",
    "teletransportarte a cualquier lugar",
    "viajar en el tiempo",
    "dormir en una hamaca",
    "pintar con los dedos de los pies"
  )

  val fr: Vector[String] = Vector(
    "voler",
    "être invisible",
    "parler aux animaux",
    "parler toutes les langues",
    "vivre dans un château",
    "vivre dans une cabane dans l'arbre",
    "nager avec les dauphins",
    "chevaucher un dragon",
    "avoir un dinosaure de compagnie",
    "avoir une licorne de compagnie",
    "manger de la pizza tous les jours",
    "manger de la glace tous les jours",
    "avoir toujours trop chaud",
    "avoir toujours trop froid",
    "être petit comme une souris",
    "être grand comme une girafe",
    "avoir la super vitesse",
    "avoir la super force",
    "lire les pensées",
    "voir l'avenir",
    "vivre sur la lune",
    "vivre sous l'eau",
    "avoir des ailes",
    "avoir une queue",
    "être un magicien",
    "être un chevalier",
    "rendre visite aux dinosaures",
    "voyager dans le futur",
    "monter à cheval",
    "monter à dos de chameau",
    "avoir une fontaine de chocolat",
    "avoir un jardin de bonbons",
    "contrôler le feu",
    "contrôler l'eau",
    "toujours porter un pyjama",
    "toujours porter des habits chic",
    "ne manger que du sucré",
    "ne manger que du salé",
    "avoir le hoquet pour toujours",
    "éternuer toutes les cinq minutes",
    "avoir un robot comme meilleur ami",
    "avoir un dragon comme meilleur ami",
    "voyager en montgolfière",
    "voyager en sous-marin",
    "qu'il pleuve toujours",
    "qu'il neige toujours",
    "être célèbre",
    "vivre dans une grotte",
    "chanter au lieu de parler",
    "danser au lieu de marcher",
    "rétrécir à la taille d'une fourmi",
    "grandir à la taille d'un géant",
    "être pirate",
    "être astronaute",
    "trouver un coffre au trésor",
    "trouver une lampe magique",
    "avoir un troisième bras",
    "avoir des yeux laser",
    "avoir un skateboard volant",
    "avoir une baguette magique",
    "ne faire que chuchoter",
    "te téléporter n'importe où",
    "voyager dans le temps",
    "dormir dans un hamac",
    "peindre avec les orteils"
  )

  val de: Vector[String] = Vector(
    "fliegen können",
    "unsichtbar sein",
    "mit Tieren reden können",
    "alle Sprachen sprechen",
    "in einem Schloss wohnen",
    "in einem Baumhaus wohnen",
    "mit Delfinen schwimmen",
    "auf einem Drachen reiten",
    "einen Dinosaurier als Haustier haben",
    "ein Einhorn als Haustier haben",
    "jeden Tag Pizza essen",
    "jeden Tag Eis essen",
    "immer zu warm haben",
    "immer zu kalt haben",
    "so klein wie eine Maus sein",
    "so groß wie eine Giraffe sein",
    "super schnell sein",
    "super stark sein",
    "Gedanken lesen können",
    "die Zukunft sehen können",
    "auf dem Mond wohnen",
    "unter Wasser wohnen",
    "Flügel haben",
    "einen Schwanz haben",
    "ein Zauberer sein",
    "ein Ritter sein",
    "die Dinosaurier besuchen",
    "in die Zukunft reisen",
    "auf einem Pferd reiten",
    "auf einem Kamel reiten",
    "einen Schokoladenbrunnen haben",
    "einen Bonbongarten haben",
    "Feuer beherrschen",
    "Wasser beherrschen",
    "immer Schlafanzug tragen",
    "immer schicke Kleidung tragen",
    "nur Süßes essen",
    "nur Salziges essen",
    "für immer Schluckauf haben",
    "alle fünf Minuten niesen",
    "einen Roboter als besten Freund haben",
    "einen Drachen als besten Freund haben",
    "mit einem Heißluftballon reisen",
    "mit einem U-Boot reisen",
    "immer Regen haben",
    "immer Schnee haben",
    "berühmt sein",
    "in einer Höhle wohnen",
    "singen statt sprechen",
    "tanzen statt gehen",
    "auf Ameisengröße schrumpfen",
    "auf Riesengröße wachsen",
    "Pirat sein",
    "Astronaut sein",
    "eine Schatztruhe finden",
    "eine Wunderlampe finden",
    "einen dritten Arm haben",
    "Laseraugen haben",
    "ein fliegendes Skateboard haben",
    "einen Zauberstab haben",
    "nur flüstern",
    "überall hin teleportieren",
    "durch die Zeit reisen",
    "in einer Hängematte schlafen",
    "mit den Zehen malen"
  )

  def forLang(lang: Lang): Vector[String] = lang match
    case Lang.Pl => pl
    case Lang.En => en
    case Lang.Es => es
    case Lang.Fr => fr
    case Lang.De => de